### ISSUE TITLE
Research on how to format javascript/html

### ISSUE THREAD

**Issue by lizhefeng** [hank1106/avocado#5]

**Comment by hank1106** [comment]
<del>Option A: use online formatter such as [this](https://www.freeformatter.com/html-formatter.html#ad-output) to format html code. Then copy the formatted HTML code to an EMPTY SPACE in atom. And then copy the formatted HTML code in Atom to designated location

**Comment by hank1106** [comment]
1. Install Atom Beautify
2. Go to Beautify settings
3. Scroll down to **JavaScript** section as it detects the React/JSX code as JavaScript
4. Change Default Beautifier to **pretty diff** (The default is JS Beautify. It formats the code in a very weird way, which is what we saw last time). 
5. Optional: check Beautify On Save (It would format everything, so I would not recommend this).

**Comment by hank1106** [comment]
Created a Wiki page for future reference. https://github.com/hank1106/avocado/wiki/Use-Beautify-atom-package-to-auto-format-JavaScript-code
